version: '3.7'

secrets:
  id_rsa:
    file:
  id_rsa.pub:
    file:
  known_hosts:
    file:

services:

  php_broadway_sensitised_es_dbal:
    environment:
      - AGGREGATE_MASTER_KEY="SS3kr3tK31"

  servicedb:
    ports:
      - 3307:3306