version: '3.7'

secrets:
  id_rsa:
    file:
  id_rsa.pub:
    file:
  known_hosts:
    file:

services:

  broadway-sensitive-serializer-php:
    environment:
      - AGGREGATE_MASTER_KEY="SS3kr3tK31"