name: "Test"

#on:
#  push:
#    branches:
#      - 'develop'
#      - 'master'

on: ["pull_request", "push"]

jobs:
  
  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests suite
        run: "./vendor/bin/phpunit --exclude-group learning --colors=always --testdox -vvv"

  code-coverage:
    name: "Code coverage"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          extensions: bcmath, ctype, gmp
          coverage: "pcov"
          ini-values: "memory_limit=-1"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: "Run unit tests (PHPUnit)"
        run: "./vendor/bin/phpunit --verbose --colors=always --coverage-text --coverage-clover ./coverage.xml"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml